# Generated by Django 4.2.1 on 2023-05-17 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0003_video_water_mark_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="video",
            field=models.FileField(upload_to="upload"),
        ),
    ]
