# Generated by Django 4.2.1 on 2023-05-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0004_alter_video_video"),
    ]

    operations = [
        migrations.AlterField(
            model_name="video",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PROCESSING", "Processing"),
                    ("ERROR", "Error"),
                    ("SUCCESS", "Success"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
