# Generated by Django 4.2.1 on 2023-05-18 02:58

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("videos", "0005_alter_video_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="water_mark",
        ),
    ]
